base_path: src
dataset: rcabench
demo_path: data/rcabench/demo
event_path: data/rcabench/events
exploration_path: exploration/gaia/pics
fasttext:
  da_method: w2v
  dataset: rcabench
  edit_count: 1
  epoch: 5
  fasttext_dir: fasttext
  minCount: 1
  nodes: ts-cancel-service ts-train-food-service ts-security-service ts-station-service
    ts-consign-service ts-config-service ts-route-plan-service ts-order-other-service
    ts-travel2-service ts-train-service ts-station-food-service ts-travel-service
    ts-auth-service ts-payment-service ts-order-service ts-contacts-service ts-route-service
    ts-price-service ts-seat-service ts-ticket-office-service mysql ts-execute-service
    ts-inside-payment-service ts-preserve-service ts-travel-plan-service ts-verification-code-service
    ts-food-service ts-ui-dashboard ts-basic-service ts-food-delivery-service ts-assurance-service
  sample_count: 1000
  save_path: fasttext/event_embedding.pkl
  supervised: true
  temp_dir: fasttext/temp
  test_path: fasttext/temp/test.txt
  text_path: parse/stratification_texts.pkl
  train_da_path: fasttext/temp/train_da.txt
  train_path: fasttext/temp/train.txt
  vector_dim: 100
feature: feature_list[0]
feature_list:
  0: TFIDF_X
  1: BOW_X
  2: NGram_X
  3: TFIDF_BOW_NGram_X
  4: TFIDF_BOW_X
  5: TFIDF_NGram_X,
  6: BOW_NGram_X
feature_path: data/rcabench/feature
he_dgl:
  N_S: 31
  TOPK_SA: 10
  Xs: sentence_embedding.pkl
  aug: false
  aug_size: 0
  batch_size: 1000
  data_dir: ''
  dataset: rcabench
  epoch: 6000
  heterogeneous: false
  lr: 0.001
  nodes: ts-cancel-service ts-train-food-service ts-security-service ts-station-service
    ts-consign-service ts-config-service ts-route-plan-service ts-order-other-service
    ts-travel2-service ts-train-service ts-station-food-service ts-travel-service
    ts-auth-service ts-payment-service ts-order-service ts-contacts-service ts-route-service
    ts-price-service ts-seat-service ts-ticket-office-service mysql ts-execute-service
    ts-inside-payment-service ts-preserve-service ts-travel-plan-service ts-verification-code-service
    ts-food-service ts-ui-dashboard ts-basic-service ts-food-delivery-service ts-assurance-service
  run_table: gt.csv
  save_dir: dgl/stratification_10
  save_model: true
  seed: 2
  text_path: parse/stratification_texts.pkl
  weight_decay: 0.0001
  win_size: 10
  win_threshold: 0.0001
label: demo2
log_path: data/rcabench/demo/log
metric_path: data/rcabench/demo/metric
parse:
  log_path: anomalies/stratification_logs.npy
  metric_path: anomalies/demo_metric.json
  nodes: ts-cancel-service ts-train-food-service ts-security-service ts-station-service
    ts-consign-service ts-config-service ts-route-plan-service ts-order-other-service
    ts-travel2-service ts-train-service ts-station-food-service ts-travel-service
    ts-auth-service ts-payment-service ts-order-service ts-contacts-service ts-route-service
    ts-price-service ts-seat-service ts-ticket-office-service mysql ts-execute-service
    ts-inside-payment-service ts-preserve-service ts-travel-plan-service ts-verification-code-service
    ts-food-service ts-ui-dashboard ts-basic-service ts-food-delivery-service ts-assurance-service
  parse_dir: parse
  save_path: parse/stratification_texts.pkl
  trace_path: anomalies/demo_trace.json
result_path: result/rcabench/analysis
sentence_embedding:
  K_S: 31
  save_path: sentence_embedding.pkl
  source_path: fasttext/event_embedding.pkl
  test_path: fasttext/temp/test.txt
  train_path: fasttext/temp/train.txt
source_data_path: data/rcabench/source_data
trace_path: data/rcabench/demo/trace
