base_path: ./
dataset: rcabench
demo_path: data/rcabench/demo
he_dgl:
  N_S: 17
  TOPK_SA: 10
  Xs: sentence_embedding.pkl
  aug: false
  aug_size: 0
  batch_size: 1000
  data_dir: ''
  dataset: rcabench
  epoch: 6000
  heterogeneous: false
  lr: 0.001
  nodes: ts-route-service ts-food-service ts-user-service ts-security-service ts-verification-code-service
    ts-ui-dashboard ts-travel-service ts-price-service ts-travel2-service ts-station-food-service
    ts-auth-service ts-order-other-service ts-seat-service ts-train-service ts-station-service
    ts-consign-service ts-order-service
  run_table: gt.csv
  save_dir: dgl/stratification_10
  save_model: true
  seed: 2
  text_path: parse/stratification_texts.pkl
  weight_decay: 0.0001
  win_size: 10
  win_threshold: 0.0001
label: demo2
