base_path: /home/nn/workspace/DiagFusion
dataset: rcabench
demo_path: data/inference/demo
fasttext:
  da_method: w2v
  dataset: rcabench
  edit_count: 1
  epoch: 5
  fasttext_dir: fasttext
  minCount: 1
  nodes: service
  sample_count: 1000
  save_path: fasttext/event_embedding.pkl
  supervised: true
  temp_dir: fasttext/temp
  test_path: fasttext/temp/test.txt
  text_path: parse/stratification_texts.pkl
  train_da_path: fasttext/temp/train_da.txt
  train_path: fasttext/temp/train.txt
  vector_dim: 100
label: demo2
parse:
  log_path: anomalies/stratification_logs.npy
  metric_path: anomalies/demo_metric.json
  nodes: service
  parse_dir: parse
  save_path: parse/stratification_texts.pkl
  trace_path: anomalies/demo_trace.json
  inference: true

